In [2]:
import numpy as np
import pandas as pd
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

# 데이터 불러오기
df_train = pd.read_csv('./heart_disease_train.csv')
df_test = pd.read_csv('./heart_disease_test.csv')

X_train = []
y_train = []

# 학습데이터 전처리
for row in df_train.iterrows():
    label = row[1][0]
    image = list(row[1][1:])
    image = np.array(image)/255
    X_train.append(image)
    y_train.append(label)

X_train = np.array(X_train)
y_train = np.array(y_train)

In [3]:
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_train)

print(y_pred[0:20], ".....")
print(y_train[0:20], ".....")
print(metrics.accuracy_score(y_train, y_pred))

## 학습데이터에 대한 예측 정확도는 100%가 나올 것이다.

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0. 1. 1. 0. 1. 1.] .....
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0. 1. 1. 0. 1. 1.] .....
1.0


In [4]:
X_test = []
y_test = []

# 테스트데이터 전처리
for row in df_test.iterrows():
    label = row[1][0]
    image = list(row[1][1:])
    image = np.array(image)/255
    X_test.append(image)
    y_test.append(label)

X_test = np.array(X_test)
y_test = np.array(y_test)

y_pred = clf.predict(X_test)

print(y_pred[0:20], ".....")
print(y_test[0:20], ".....")
print(metrics.accuracy_score(y_test, y_pred))

# 테스트데이터에 대한 예측 정확도 역시 100%가 나온다

[0. 1. 0. 0. 1. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0.] .....
[0. 1. 0. 0. 1. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0.] .....
1.0
